# Generated by Django 5.2.1 on 2026-01-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="token",
            field=models.CharField(max_length=64),
        ),
    ]
